version: "3"
services:
  website:
    image: website-krsmanovic:20210710
    container_name: website-backend
    restart: unless-stopped
    expose:
      - 2021
    volumes:
      - ./docker-website:/website
      - ./docker-website/error.log:/usr/src/website/error.log
  nginx:
    image: nginx-krsmanovic:20210710
    container_name: nginx-ingress
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker-nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt